version: '2'
services:
  api:
    build: us-census-api
    volumes:
      - ./us-census-api:/app:Z
    ports:
      - "9292:9292"
    environment:
      - RACK_ENV=production
      - DATABASE_URL=sqlite://data/us-census.db
      - APP_URL=http://localhost:8000

  app:
    build: us-census-app
    volumes:
      - ./us-census-app/app:/home/census/app:Z
    ports:
      - "8000:8000"
    links:
      - api
