# frozen_string_literal: true

require 'rake/testtask'

task :default do
  puts `rake -T`
end

Rake::TestTask.new(:spec) do |t|
  t.pattern = 'spec/*_spec.rb'
  t.warning = false
end

desc 'delete files or folders in casset or cloned repositories'
namespace :wipe do
  desc 'wipe cassettes'
  task :cassettes do
    sh 'rm spec/fixtures/cassettes/*.yml' do |ok, _|
      puts(ok ? 'Cassettes deleted' : 'No cassettes found')
    end
  end
end

namespace :quality do

  desc 'run all quality checks'
  task all: [:spec, :rubocop, :flog, :flay]

  task :flog do
    sh 'flog ./'
  end

  task :flay do
    sh 'flay'
  end

  task :rubocop do
    sh 'rubocop'
  end
end
